### PR TITLE
update to os tickets

### PR DESCRIPTION
**Pull request by wxtim**
My updated version of Oliver's thoughts on the work on Platforms.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Perhaps better to write these up as issues which we can assign / raise PRs against than a static document.

**Comment by dpmatthews** [comment]
> Perhaps better to write these up as issues which we can assign / raise PRs against than a static document.

I think either way is fine. We already have cylc/cylc-flow#3421 to refer to.

**Comment by hjoliver** [comment]
Could @wxtim or @oliver-sanders explain the "work on master" aspects of this?  We don't ever work directly on master (as opposed to feature branches that get merged to master) so I wonder if I'm misunderstanding this.

**Comment by wxtim** [comment]
> Could @wxtim or @oliver-sanders explain the "work on master" aspects of this? We don't ever work directly on master (as opposed to feature branches that get merged to master) so I wonder if I'm misunderstanding this.

Clarification - "working on master" in this context refers to creating small(ish) feature branches and getting these accepted onto master straight off the bat. We're using feature branches to describe a branch on which we work for some time creating subsidiary PR's before merging to master.

**Pull request merged**
