### PR TITLE
how to debug pytest despite distribution

### PR DESCRIPTION
**Pull request by wxtim**
How to debug python tests.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Heck, didn't know we had testing documentation here.

It think it would probs be better to copy this information into the README files in `cylc-flow/tests/` as these docs are highly likely to get out of date as they are in the wrong repo and contributors are unlikely to find them.

**Comment by hjoliver** [comment]
> It think it would probs be better to copy this information into the README files in cylc-flow/tests/ as these docs are highly likely to get out of date as they are in the wrong repo and contributors are unlikely to find them.

I agree.  Do you want to do that @oliver-sanders ? (As recent author of said README files).

(BTW as far as documentation goes, cylc-admin can be used as a temporary holding tank pending decisions on final resting place).

**Comment by wxtim** [comment]
> Heck, didn't know we had testing documentation here.

We didn't - this came from out internal docs (metomi-docs) and was updated for Dave. I originally wrote these for Mel distilling things you'd told me about debugging the test framework. There's nothing in these requiring them being in a private repo.

**Comment by hjoliver** [comment]
> Happy to move this and replace this PR with one in cylc-flow and close this one.

@wxtim I'll merge this change here, so you have a single source to work from.

**Pull request merged**
