### PR TITLE
Suggest coding styles for the meeting agenda of Mar/2019

### PR DESCRIPTION
**Pull request by kinow**
Quick pull request with a suggestion for coding conventions for our repositories. Our Python code is being rewritten in some packages, so this is a good time to establish code conventions to be followed.

These conventions could also be re-used in the Cylc UI Server and other Python projects.

There are already a few docstrings, but some in the google format, some in the old PEP 257, some in the docstring supported by PyCharm (_cough, cough_, sorry).

I think ideally we need one that can be used for documentation, but also by syntax highlighters and IDE's - the more tools supported, the merrier IMO.

Cheers
Bruno

### CODE REVIEW

**Comment by kinow** [comment]
This silly GitHub UI... I thought the branch would be created in my repo. So will delete the `kinow-patch-1` branch once closed/merged.

**Comment by matthewrmshin** [comment]
Maybe worth filling in the full set of community profile e.g. https://github.com/cylc/cylc-admin/community as well.

And should we use something like [Black](https://github.com/ambv/black)?

**Comment by kinow** [comment]
Good idea @matthewrmshin , will update the branch in the next minutes. Thanks!

**Comment by hjoliver** [comment]
Here's the cylc/cylc one: https://github.com/cylc/cylc/community

We have CONTRIBUTING.md now, only code of conduct is missing (not sure we need issue and PR templates? ... maybe if we start getting much from totally new people).

But I guess we need the same for the other new projects.

**Comment by hjoliver** [comment]
(Branch deleted)

**Comment by kinow** [comment]
Thanks @hjoliver !

**Pull request merged**
